export const SET_PROJECTS = "SET_PROJECTS";
export const SET_TOTAL = "SET_TOTAL";
export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
